---
abstract: 'Catalog of HTML and XHTML DTDs'
author:
  - 'Eric Brine, C<< <ikegami@adaelis.com> >>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110580'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Catalogs-HTML
provides:
  XML::Catalogs::HTML:
    file: lib/XML/Catalogs/HTML.pm
    version: v1.0.3
requires:
  File::ShareDir: 1.00
  XML::Catalogs: 0
  version: 0
version: v1.0.3
